version: '3.4'

services:
  computacaografica:
    image: computacaografica
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3002:3002
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
