version: '3.4'

services:
  computacaografica:
    image: computacaografica
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002
